# The Example of Compiling LaTeX File
# In your latex repository, make .github/workflows/main.yml like below.
# You only have to change `LATEX_FILE_NAME` as your tex file.

on:
  push:
    branches:
      - "test"
  workflow_dispatch:
jobs:
#   build-latex:
#     runs-on: ubuntu-latest
#     name: Example of compiling pdf
#     steps:
#       # make pdf
#       # LATEX_FILE_NAME -> main.pdf generated
#       - name: Set up Git repository
#         uses: actions/checkout@v2
#       - name: Compile Tex File
#         id: compile_tex_file
#         uses: tsukuba-mas/platex-action@main
#         with:
#           LATEX_FILE_NAME: "main.tex"
  deploy:
    name: upload-to-googledrive
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: arcatdmz/texlive
#     needs: build-latex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build PDF file
        run: latexmk -pdf && latexmk -c && mkdir -p docs && cp *.pdf ./docs/
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1.2.1
        with:
          google-client-id: ${{ secrets.SKICKA_CLIENT_ID }}
          google-client-secret: ${{ secrets.SKICKA_CLIENT_SECRET }}
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: ./main.pdf
          upload-to: /
# Create Release
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#         with:
#           tag_name: ${{github.ref}}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Compiled PDF ${{github.ref}}
#           draft: false
#           prerelease: false
      # Upload Asset main.pdf
#       - name: Upload Release Asset
#         id: upload_release_asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./main.pdf
#           asset_name: main.pdf
#           asset_content_type: application/pdf
